name: stl-lra
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8
  - matplotlib
  - notebook

  # pandas and its dependencies
  - pandas
  - numexpr
  - bottleneck
  - openpyxl

  # geo
  - geopandas=0.9
  - descartes

  # data retrieval
  - requests
  - beautifulsoup4

  # style
  - isort
  - black

  - pip
  - pip:
      - "git+https://github.com/fangchenli/opendbf.git"
