name: stl-lra
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8
  - matplotlib
  - notebook

  # pandas and its dependencies
  - pandas
  - numexpr
  - bottleneck
  - xlrd

  # geo
  - geopandas=0.8
  - descartes

  # data retrieval
  - requests
  - beautifulsoup4

  # style
  - isort
  - black
