name: stl-lra
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8
  - pandas
  - xlrd
  - descartes
  - matplotlib
  - geopandas=0.8
  - notebook

  # data retrieval
  - requests
  - beautifulsoup4

  # linting
  - isort
  - black

  - pip
  - pip:
      - psycopg2